spring:
  application:
    name: simple-spring-statemachine
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  flyway:
    schemas: public
    validate-on-migrate: false
    baseline-on-migrate: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/task-db
    driver-class-name: org.postgresql.Driver
    maximumPoolSize: 10
    minimumIdle: 5
    idleTimeout: 10000

logging:
  pattern:
    console: "%clr(%-5level) %d{yyy-MM-dd HH:mm:ss.SS} [%thread] %clr([%logger{0}.%M]){cyan} %m%wEx%n"
    file: "[%-5level] %d{yyy-MM-dd HH:mm:ss.SS} [%thread] [%-26logger{26}] %m%wEx%n"